kind: pipeline
type: docker
name: default

platform:
  arch: arm64

steps:
- name: build
  image: golang:latest
  commands:
  - go build
  
- name: test
  image: golang:latest
  commands:
  - go test
